from PyQt5 import QtCore, QtGui, QtWidgets
from utils.drawing.Plot2 import Plot
from DrawTool import DrawTool
from CmdBar import CmdBar
from PropertiesBar import PropertiesBar


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        font = QtGui.QFont()
        font.setFamily("Alegreya Sans SC")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #3C4048;")
        self.centralwidget.setObjectName("centralwidget")

        self.plot = Plot(self.centralwidget)

        self.draw_bar = QtWidgets.QWidget(self.centralwidget)
        self.draw_bar.setGeometry(QtCore.QRect(20, 19, 121, 681))
        self.draw_bar.setStyleSheet("background-color: #EAEAEA;\n"
                                    "border-radius: 10px;")
        self.draw_bar.setObjectName("draw_bar")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.draw_bar)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.draw_bar_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.draw_bar_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.draw_bar_layout.setContentsMargins(10, 5, 10, 5)
        self.draw_bar_layout.setSpacing(10)
        self.draw_bar_layout.setObjectName("draw_bar_layout")

        draw_tools_names = ['Point', 'Segment', 'Line', 'Plane', 'Cylinder', 'PL']
        draw_tools = list()

        for name in draw_tools_names:
            draw_tool = DrawTool(name)
            draw_tools.append(draw_tool)
            self.draw_bar_layout.addWidget(
                draw_tool.set_on_click_listener(self.plot.draw))

        self.cmd_bar = CmdBar(self.centralwidget).set_plot(self.plot)

        self.plot.printToCommandLine.connect(self.cmd_bar.set_text)

        self.tool_bar = QtWidgets.QWidget(self.centralwidget)
        self.tool_bar.setGeometry(QtCore.QRect(890, 19, 171, 111))
        self.tool_bar.setStyleSheet("background-color: #EAEAEA; border-radius: 10px;")
        self.tool_bar.setObjectName("tool_bar")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tool_bar)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 171, 111))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.tool_bar_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.tool_bar_layout.setContentsMargins(15, 8, 15, 8)
        self.tool_bar_layout.setSpacing(0)
        self.tool_bar_layout.setObjectName("tool_bar_layout")
        self.tool_bar_tool_3 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self.tool_bar_tool_3.setObjectName("tool_bar_tool_3")
        self.widget1 = QtWidgets.QWidget(self.tool_bar_tool_3)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 141, 32))
        self.widget1.setObjectName("widget1")
        self.tool_bar_tool_3_layout = QtWidgets.QHBoxLayout(self.widget1)
        self.tool_bar_tool_3_layout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.tool_bar_tool_3_layout.setContentsMargins(0, 0, 0, 0)
        self.tool_bar_tool_3_layout.setSpacing(5)
        self.tool_bar_tool_3_layout.setObjectName("tool_bar_tool_3_layout")
        self.tool_bar_tool_3_icon = QtWidgets.QLabel(self.widget1)
        self.tool_bar_tool_3_icon.setMaximumSize(QtCore.QSize(30, 30))
        self.tool_bar_tool_3_icon.setText("")
        self.tool_bar_tool_3_icon.setPixmap(QtGui.QPixmap(":/img/img/intersection_icon.png"))
        self.tool_bar_tool_3_icon.setScaledContents(True)
        self.tool_bar_tool_3_icon.setObjectName("tool_bar_tool_3_icon")
        self.tool_bar_tool_3_layout.addWidget(self.tool_bar_tool_3_icon)
        self.tool_bar_tool_3_label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Alegreya Sans SC ExtraBold")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.tool_bar_tool_3_label.setFont(font)
        self.tool_bar_tool_3_label.setStyleSheet("color: #00ABB3;")
        self.tool_bar_tool_3_label.setObjectName("tool_bar_tool_3_label")
        self.tool_bar_tool_3_layout.addWidget(self.tool_bar_tool_3_label)
        self.tool_bar_layout.addWidget(self.tool_bar_tool_3)
        self.tool_bar_tool_2 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self.tool_bar_tool_2.setObjectName("tool_bar_tool_2")
        self.widget2 = QtWidgets.QWidget(self.tool_bar_tool_2)
        self.widget2.setGeometry(QtCore.QRect(0, 0, 141, 32))
        self.widget2.setObjectName("widget2")
        self.tool_bar_tool_2_layout = QtWidgets.QHBoxLayout(self.widget2)
        self.tool_bar_tool_2_layout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.tool_bar_tool_2_layout.setContentsMargins(0, 0, 0, 0)
        self.tool_bar_tool_2_layout.setSpacing(5)
        self.tool_bar_tool_2_layout.setObjectName("tool_bar_tool_2_layout")
        self.tool_bar_tool_2_icon = QtWidgets.QLabel(self.widget2)
        self.tool_bar_tool_2_icon.setMaximumSize(QtCore.QSize(30, 30))
        self.tool_bar_tool_2_icon.setText("")
        self.tool_bar_tool_2_icon.setPixmap(QtGui.QPixmap(":/img/img/angle_icon.png"))
        self.tool_bar_tool_2_icon.setScaledContents(True)
        self.tool_bar_tool_2_icon.setObjectName("tool_bar_tool_2_icon")
        self.tool_bar_tool_2_layout.addWidget(self.tool_bar_tool_2_icon)
        self.tool_bar_tool_2_label = QtWidgets.QLabel(self.widget2)
        self.tool_bar_tool_2_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Alegreya Sans SC ExtraBold")
        font.setPointSize(7)
        self.tool_bar_tool_2_label.setFont(font)
        self.tool_bar_tool_2_label.setStyleSheet("color: #00ABB3;")
        self.tool_bar_tool_2_label.setObjectName("tool_bar_tool_2_label")
        self.tool_bar_tool_2_layout.addWidget(self.tool_bar_tool_2_label)
        self.tool_bar_layout.addWidget(self.tool_bar_tool_2)
        self.tool_bar_tool_1 = QtWidgets.QWidget(self.verticalLayoutWidget_5)
        self.tool_bar_tool_1.setObjectName("tool_bar_tool_1")
        self.widget3 = QtWidgets.QWidget(self.tool_bar_tool_1)
        self.widget3.setGeometry(QtCore.QRect(0, 0, 141, 32))
        self.widget3.setObjectName("widget3")
        self.tool_bar_tool_1_layout = QtWidgets.QHBoxLayout(self.widget3)
        self.tool_bar_tool_1_layout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.tool_bar_tool_1_layout.setContentsMargins(0, 0, 0, 0)
        self.tool_bar_tool_1_layout.setSpacing(5)
        self.tool_bar_tool_1_layout.setObjectName("tool_bar_tool_1_layout")
        self.tool_bar_tool_1_icon = QtWidgets.QLabel(self.widget3)
        self.tool_bar_tool_1_icon.setEnabled(True)
        self.tool_bar_tool_1_icon.setMaximumSize(QtCore.QSize(30, 30))
        self.tool_bar_tool_1_icon.setText("")
        self.tool_bar_tool_1_icon.setPixmap(QtGui.QPixmap(":/img/img/ruler_icon.png"))
        self.tool_bar_tool_1_icon.setScaledContents(True)
        self.tool_bar_tool_1_icon.setObjectName("tool_bar_tool_1_icon")
        self.tool_bar_tool_1_layout.addWidget(self.tool_bar_tool_1_icon)
        self.tool_bar_tool_1_label = QtWidgets.QLabel(self.widget3)
        self.tool_bar_tool_1_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Alegreya Sans SC ExtraBold")
        font.setPointSize(7)
        self.tool_bar_tool_1_label.setFont(font)
        self.tool_bar_tool_1_label.setStyleSheet("color: #00ABB3;")
        self.tool_bar_tool_1_label.setObjectName("tool_bar_tool_1_label")
        self.tool_bar_tool_1_layout.addWidget(self.tool_bar_tool_1_label)
        self.tool_bar_layout.addWidget(self.tool_bar_tool_1)

        # TODO: PROPERTIES BAR IS HERE :)

        self.properties_bar = PropertiesBar(self.centralwidget)

        # TODO: INSPECTOR BAR IS HERE :)

        self.inspector_bar = QtWidgets.QWidget(self.centralwidget)
        self.inspector_bar.setGeometry(QtCore.QRect(890, 500, 171, 201))
        self.inspector_bar.setStyleSheet("background-color: #EAEAEA; border-radius: 10px;")
        self.inspector_bar.setObjectName("inspector_bar")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.inspector_bar)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 171, 49))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.inspector_bar_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.inspector_bar_layout.setContentsMargins(15, 10, 15, 0)
        self.inspector_bar_layout.setObjectName("inspector_bar_layout")
        self.inspector_bar_object_1 = QtWidgets.QWidget(self.verticalLayoutWidget_3)
        self.inspector_bar_object_1.setObjectName("inspector_bar_object_1")
        self.widget5 = QtWidgets.QWidget(self.inspector_bar_object_1)
        self.widget5.setGeometry(QtCore.QRect(0, 0, 141, 22))
        self.widget5.setObjectName("widget5")
        self.inspector_bar_object_1_layout = QtWidgets.QHBoxLayout(self.widget5)
        self.inspector_bar_object_1_layout.setContentsMargins(0, 0, 0, 0)
        self.inspector_bar_object_1_layout.setSpacing(5)
        self.inspector_bar_object_1_layout.setObjectName("inspector_bar_object_1_layout")
        self.inspector_bar_object_1_icon = QtWidgets.QLabel(self.widget5)
        self.inspector_bar_object_1_icon.setMaximumSize(QtCore.QSize(20, 20))
        self.inspector_bar_object_1_icon.setText("")
        self.inspector_bar_object_1_icon.setPixmap(QtGui.QPixmap(":/img/img/inspector_bar_object_icon.png"))
        self.inspector_bar_object_1_icon.setScaledContents(True)
        self.inspector_bar_object_1_icon.setObjectName("inspector_bar_object_1_icon")
        self.inspector_bar_object_1_layout.addWidget(self.inspector_bar_object_1_icon)
        self.inspector_bar_object_1_label = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setFamily("Alegreya Sans SC ExtraBold")
        font.setPointSize(7)
        self.inspector_bar_object_1_label.setFont(font)
        self.inspector_bar_object_1_label.setStyleSheet("color: #00ABB3;")
        self.inspector_bar_object_1_label.setObjectName("inspector_bar_object_1_label")
        self.inspector_bar_object_1_layout.addWidget(self.inspector_bar_object_1_label)
        self.inspector_bar_layout.addWidget(self.inspector_bar_object_1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("DescriptiveGeometry", "Начертательная геометрия"))
        # self.draw_tool_7_label.setText(_translate("DescriptiveGeometry", "PointW"))
        # self.draw_tool_6_label.setText(_translate("DescriptiveGeometry", "Segment"))
        # self.draw_tool_5_label.setText(_translate("DescriptiveGeometry", "Line"))
        # self.draw_tool_4_label.setText(_translate("DescriptiveGeometry", "Circle"))
        # self.draw_tool_3_label.setText(_translate("DescriptiveGeometry", "Tor"))
        # self.draw_tool_2_label.setText(_translate("DescriptiveGeometry", "Cylinder"))
        # self.draw_tool_1_label.setText(_translate("DescriptiveGeometry", "RS"))
        # self.cmd_bar_past.setText(_translate("DescriptiveGeometry",
        #                                      ">>> draw(*[segment(point(i, i*2, i*3), point(0, 0, 0)) for i in range(10_000_000)])"))
        # self.cmd_bar_present.setText(_translate("DescriptiveGeometry",
        #                                         "<class \'utils.drawing.plot.Plot\'> objects have been successfully drawn"))
        # self.cmd_bar_future.setText(_translate("DescriptiveGeometry", ">>> save()"))
        self.tool_bar_tool_3_label.setText(_translate("DescriptiveGeometry", "Intersection"))
        self.tool_bar_tool_2_label.setText(_translate("DescriptiveGeometry", "Angle"))
        self.tool_bar_tool_1_label.setText(_translate("DescriptiveGeometry", "Ruler"))
        # self.label.setText(_translate("DescriptiveGeometry", "Name"))
        # self.lineEdit.setText(_translate("DescriptiveGeometry", "A"))
        # self.label_2.setText(_translate("DescriptiveGeometry", "Color"))
        # self.label_3.setText(_translate("DescriptiveGeometry", "Layer"))
        # self.lineEdit_2.setText(_translate("DescriptiveGeometry", "1"))
        # self.label_4.setText(_translate("DescriptiveGeometry", "Thickness"))
        # self.comboBox.setItemText(0, _translate("DescriptiveGeometry", "light"))
        # self.comboBox.setItemText(1, _translate("DescriptiveGeometry", "medium"))
        # self.comboBox.setItemText(2, _translate("DescriptiveGeometry", "bold"))
        # self.properties_bar_object_1_label.setText(_translate("DescriptiveGeometry", "Tube radius"))
        self.inspector_bar_object_1_label.setText(_translate("DescriptiveGeometry", "A: Cylinder"))


import resources_rc
